"""Help-text contract (CLI_CONTRACT §10): every leaf command documents examples.

§10 requires each command's ``--help`` to carry purpose, usage, 2-3 examples, flags,
output notes · safety note. The flag table (purpose/usage/flags) is generated by typer;
the part that silently rots is the hand-written ``Examples:`` block — so we pin exactly
that, for every command the CLI actually exposes (enumerated from the click tree, not a
hand-maintained list, so a new command without examples fails this test).
"""

from __future__ import annotations

from tests.conftest import RunCli, leaf_command_paths

LEAVES = leaf_command_paths()


def test_leaf_enumeration_is_sane() -> None:
    # Sanity: the walk found the real surface, not an empty/degenerate set.
    flat = {".".join(p) for p in LEAVES}
    assert {"init", "doctor", "ingest", "authors.find", "export.context"} <= flat
    assert len(LEAVES) >= 25


def test_each_command_help_has_examples(run_cli: RunCli) -> None:
    missing: list[str] = []
    for path in LEAVES:
        result = run_cli(*path, "--help")
        assert result.exit_code == 0, f"`{' '.join(path)} --help` exited {result.exit_code}"
        if "Examples:" not in result.stdout:
            missing.append(" ".join(path))
    assert not missing, f"commands missing an Examples: block in --help: {missing}"
